---
title: "Tesla Presentation"
output:
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---

```{r}

#libraries
library(dplyr)
library(tidyr)
library(ggplot2)
library(scales)


#reading in the data

df <- read.csv("C:\\Users\\iyanu\\Downloads\\LEARNING DATA ANALYTICS\\Learning R with Alex\\Final Project\\Files\\Electric_Vehicle_Population_Data.csv")

clean_df <- df %>%
  rename_all(~ gsub("\\.","_", .)) %>%
  mutate(
    Base_MSRP = as.numeric(Base_MSRP),
    Tesla = ifelse(Make == "TESLA", "TESLA", "OTHER")
  )


# 1. What percentage of EV's in Washington are Teslas?
#to get this we do a basic percentage: tesla/all vehicles * 100

total_vehicles <- nrow(clean_df)
tesla_vehicles <- clean_df %>% filter(Tesla == "TESLA") %>% nrow()

tesla_market_share <- round(tesla_vehicles/total_vehicles * 100, 1)

#Percentage of Tesla's EV's in Washington is low at 42.9 percent compared to other vehicles


# 2. Top Tesla Models Selling in the area
# i.e how much are we making from these models?

make_model_sold <- clean_df  %>%
  filter(Tesla == "TESLA") %>%
  group_by(Make, Model) %>%
  summarise(count_sold = n(), .groups = "drop") %>%
  arrange(desc(count_sold))

str(clean_df)
summary(clean_df)

msrp_per_year <- clean_df %>%
  filter(Base_MSRP > 0) %>%
  filter(Tesla == "TESLA") %>%
  group_by(Model_Year, Make, Model) %>%
  summarise(min(Base_MSRP)) %>%
  arrange(Model_Year, Make, Model)

#There were'nt good base msrp in this dataset so i'm going to read in csv


df_tesla_prices <- read.csv("C:\\Users\\iyanu\\Downloads\\LEARNING DATA ANALYTICS\\Learning R with Alex\\Final Project\\Files\\Tesla_Current_Base_Prices.csv")

#transform data to upper

df_tesla_prices <- df_tesla_prices %>%
  mutate(
    Model = toupper(Model)
  )
  
#getting our numbers

Top_Tesla_Models_Priced <- make_model_sold %>%
  left_join(df_tesla_prices, by = "Model") %>%
  mutate(
    Estimated_revenue = as.numeric(count_sold) * as.numeric(Base_Price_USD)
  )

#final estimates for lifetime sales
Top_Tesla_Models_Priced <- Top_Tesla_Models_Priced %>%
  filter(!is.na(Estimated_revenue)) %>%
  group_by(Model) %>%
  slice_min(Base_Price_USD) %>%
  ungroup()


#Tesla sold by Year Data
tesla_sold_by_year <- clean_df %>%
  filter(Tesla == "TESLA") %>%
  group_by(Model_Year) %>%
  summarise(count = n()) %>%
  arrange(Model_Year)

# 3. Tesla vs Competitors - Range and MSRP
# - AVG and Median

#AVG Range

Avg_Range_For_EVs <- clean_df %>%
  filter(Electric_Vehicle_Type == "Battery Electric Vehicle (BEV)",
         Electric_Range != 0,
         Base_MSRP != 0) %>%
  group_by(Tesla) %>%
  summarise(AVG_Range = mean(Electric_Range),
            AVG_MSRP =mean(Base_MSRP))


#Median Range

Median_Range_For_EVs <- clean_df %>%
  filter(Electric_Vehicle_Type == "Battery Electric Vehicle (BEV)",
         Electric_Range != 0,
         Base_MSRP != 0) %>%
  group_by(Tesla) %>%
  summarise(Median_Range = median(Electric_Range),
            Median_MSRP =median(Base_MSRP))

#MSRP Data isn't fully populated and may skew results



# 4. BHEV vs BEV Trends

PHEV_vs_BEV <- clean_df %>%
  group_by(Model_Year, Electric_Vehicle_Type) %>%
  summarise(Count = n(), .groups = "drop")

# 5. Top Electric Utilities in Washington for Tesla

Utility_Count_for_Teslas <- clean_df %>%
  filter(Tesla == "TESLA") %>%
  group_by(Electric_Utility) %>%
  summarise(Count = n(), .groups = "drop") %>%
  arrange(desc(Count)) %>%
  head(5)

```


## Tesla Market Share in Washington (%)

```{r}
market_df <- data.frame(
  Group = c("TESLA", "OTHER"),
  Market_Share = c(tesla_market_share, 100 - tesla_market_share)
)

market_df <- market_df %>%
  mutate(
    Label = paste0(Market_Share, "%"),
    ypos = cumsum(Market_Share) - 0.5 * Market_Share
  )

ggplot(market_df, aes(x = "", y = Market_Share, fill = Group)) +
  geom_col(width = 1) +
  coord_polar("y") +
  geom_text (aes(y = ypos, label = Label))+
  labs(title = "Tesla Market Share in Washington (%)")+
  theme_void()

```


## Tesla Models Sold - All Time

```{r}
ggplot(make_model_sold, aes(x = reorder(Model, count_sold), y = count_sold)) +
  geom_col(fill = "dodgerblue") +
  coord_flip() +
  labs(title = "Tesla Models Sold - All Time") +
  theme_minimal()


```


## Estimated Revenue Per Model
```{r}

ggplot(Top_Tesla_Models_Priced, aes(x = reorder(Model, Estimated_revenue), y = Estimated_revenue)) +
  geom_col(fill = "forestgreen") +
  coord_flip() +
  labs(title = "Estimated Revenue Per Model") +
  scale_y_continuous(labels = label_comma())
  theme_minimal()
  
```

## Tesla Vehicle Sold By Year
```{r}

ggplot(tesla_sold_by_year, aes(x = Model_Year, y = count)) +
  geom_line(color = "dodgerblue", size = 1) +
  geom_point(color = "red", size = 2) +
  labs(title = " Tesla Vehicles Sold by Year") +
  theme_minimal()


```


## AVG Electric Range (BEV)

```{r}
#Range
ggplot(Avg_Range_For_EVs, aes(x = Tesla, y = AVG_Range, fill = Tesla)) +
  geom_col() +
  labs(title = "AVG Electric Range (BEV)") +
  theme_minimal()

```


## AVG MSRP (BEV)

```{r}
#MSRP
ggplot(Avg_Range_For_EVs, aes(x = Tesla, y = AVG_MSRP, fill = Tesla)) +
  geom_col() +
  labs(title = "AVG MSRP (BEV)") +
  theme_minimal()

```

## PHEV vs BEV Trends Over Time

```{r}

ggplot(PHEV_vs_BEV, aes(x = Model_Year, y = Count, colour = Electric_Vehicle_Type)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  labs(title = "PHEV vs BEV Trends Over Time") +
  theme_minimal()


```

## Top Electric Utilities for Tesla in Washington

```{r}

    ggplot(Utility_Count_for_Teslas, aes(x = reorder(Electric_Utility, Count), y = Count)) +
    geom_col( color = "steelblue") +
    coord_flip()+
    labs(title = "Top Electric Utilities for Tesla in Washington") +
    theme_minimal()

```






































































